# Generated by Django 3.1.6 on 2021-05-30 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=6)),
                ('address', models.CharField(max_length=40)),
                ('date_of_birth', models.DateField()),
                ('religion', models.CharField(max_length=10)),
                ('nationality', models.CharField(max_length=15)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-')], max_length=10)),
                ('biodata', models.TextField()),
                ('profession', models.CharField(choices=[('Serviceman', 'Serviceman'), ('Businessman', 'Businessman'), ('Worker', 'Worker'), ('Others', 'Others')], max_length=15)),
                ('image', models.ImageField(default='avater.jpg', upload_to='userprofile/images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
