# Generated by Django 3.1.6 on 2021-05-29 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_contact_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatePost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('salary', models.FloatField()),
                ('avaliable', models.BooleanField()),
                ('category', models.CharField(choices=[('Teacher', 'Teacher'), ('Student', 'Student'), ('Gurdian', 'Gurdian'), ('Instituate', 'Instituate')], max_length=200)),
                ('image', models.ImageField(default='avater.jpg', upload_to='media/image')),
            ],
        ),
    ]
