# Generated by Django 3.1.6 on 2021-05-29 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210529_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createpost',
            name='image',
            field=models.ImageField(upload_to='blog/images'),
        ),
    ]
