# Generated by Django 3.1.6 on 2021-05-29 13:38

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210529_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class_in',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='createpost',
            name='subject',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Bangla', 'Bangla'), ('English', 'English'), ('Hindi', 'Hindi'), ('Urdu', 'Urdu'), ('Arabic', 'Arabic')], default='Bangla', max_length=500),
        ),
        migrations.AddField(
            model_name='createpost',
            name='class_in',
            field=models.ManyToManyField(related_name='class_set', to='blog.Class_in'),
        ),
    ]
