# Generated by Django 3.1.6 on 2021-05-30 05:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0011_createpost_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CreatePost',
            new_name='Post',
        ),
    ]
